---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: gs-frontend
spec:
  destination:
    name: gs-frontend
  sources:
    - name: ingress-gateway
      action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: gs-backend
spec:
  destination:
    name: gs-backend
  sources:
    - name: gs-frontend
      # action: allow
      permissions:
        - action: allow
          http:
            pathPrefix: /
            # methods: ['GET', 'PUT', 'POST', 'DELETE', 'HEAD']
            methods: ['GET', 'HEAD']
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: deny-all
spec:
  destination:
    name: "*"
  sources:
    - name: "*"
      action: deny
