apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: gs-frontend
  namespace: default
spec:
  protocol: http`
  upstreamConfig:
    defaults:
      limits:
        maxConnections: 1
        maxPendingRequests: 1
        maxConcurrentRequests: 1
      # passiveHealthCheck:
      #   interval: 10s
      #   maxFailures: 5
  #   overrides:
  #     - name: "gs-backend"
  #       protocol: "http"
  #       connectTimeoutMs: 1000
  #       passiveHealthCheck:
  #         interval: 10s
  #         maxFailures: 5
  #       limits:
  #         maxConnections: 1
  #         maxPendingRequests: 1
  #         maxConcurrentRequests: 1
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: gs-backend
spec:
  protocol: http